# Generated by Django 5.1 on 2024-08-27 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks_List', '0002_list_emoji'),
        ('tasks', '0003_rename_title_task_tittle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='tasks',
            field=models.ManyToManyField(null=True, to='tasks.task'),
        ),
    ]
