# Generated by Django 5.0.4 on 2024-08-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks_List', '0002_list_emoji'),
        ('users', '0002_rename_user_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='listas',
            field=models.ManyToManyField(to='Tasks_List.list'),
        ),
    ]
