# Generated by Django 5.0.4 on 2024-08-26 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_users_listas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user',
        ),
    ]
